name: Update Toffee Channels

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  actions: write

jobs:
  update-channels:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install missing libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libnss3 libgconf-2-4
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests beautifulsoup4 webdriver-manager
        
    - name: Display Chrome and ChromeDriver versions
      run: |
        google-chrome --version
        chromedriver --version
        
    - name: Debug Selenium
      run: |
        export DISPLAY=:99
        sudo Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        python toffee_scraper.py
      env:
        PYTHONUNBUFFERED: 1
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add toffee_channels.m3u
        timestamp=$(date -u)
        git commit -m "Auto Update Channels: ${timestamp}" || exit 0
        git push
